version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crp5a700iald4ruj6tg5/catgpt:df6e210da34c5a1fd8f349229cae0c2ba71f12a9"
    restart: always
    network_mode: "host"

  unifiedagent:
    container_name: unifiedagent
    image: "cr.yandex/yc/unified-agent"
    environment:
      FOLDER_ID: "${folder_id}"
    restart: always
    network_mode: "host"
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d