name: Yandex app CI

on:
  push:
    branches:
     - main

env:
  IMAGE: crp5a700iald4ruj6tg5/catgpt
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YCR_JSON }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$IMAGE:$IMAGE_TAG .
          docker push cr.yandex/$IMAGE:$IMAGE_TAG
